# Generated by Django 4.2.23 on 2025-08-05 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_time_to_cook_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='creator',
            new_name='author',
        ),
    ]
